// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: RBAC.proto

package RBAC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool bool `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{0}
}

func (x *Bool) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

type Bools struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bools []bool `protobuf:"varint,1,rep,packed,name=Bools,proto3" json:"Bools,omitempty"`
}

func (x *Bools) Reset() {
	*x = Bools{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bools) ProtoMessage() {}

func (x *Bools) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bools.ProtoReflect.Descriptor instead.
func (*Bools) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{1}
}

func (x *Bools) GetBools() []bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

type Uid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Uid) Reset() {
	*x = Uid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uid) ProtoMessage() {}

func (x *Uid) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uid.ProtoReflect.Descriptor instead.
func (*Uid) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{2}
}

func (x *Uid) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Uids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
}

func (x *Uids) Reset() {
	*x = Uids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uids) ProtoMessage() {}

func (x *Uids) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uids.ProtoReflect.Descriptor instead.
func (*Uids) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{3}
}

func (x *Uids) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Roles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *Roles) Reset() {
	*x = Roles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roles) ProtoMessage() {}

func (x *Roles) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roles.ProtoReflect.Descriptor instead.
func (*Roles) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{5}
}

func (x *Roles) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{6}
}

type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` //路径名
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{7}
}

func (x *Path) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Paths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *Paths) Reset() {
	*x = Paths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paths) ProtoMessage() {}

func (x *Paths) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paths.ProtoReflect.Descriptor instead.
func (*Paths) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{8}
}

func (x *Paths) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type RolePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RolePath) Reset() {
	*x = RolePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePath) ProtoMessage() {}

func (x *RolePath) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePath.ProtoReflect.Descriptor instead.
func (*RolePath) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{9}
}

func (x *RolePath) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RolesPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *RolesPaths) Reset() {
	*x = RolesPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesPaths) ProtoMessage() {}

func (x *RolesPaths) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesPaths.ProtoReflect.Descriptor instead.
func (*RolesPaths) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{10}
}

func (x *RolesPaths) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RolesPaths) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{11}
}

func (x *UserRole) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsersRoles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids  []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Roles []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UsersRoles) Reset() {
	*x = UsersRoles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RBAC_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersRoles) ProtoMessage() {}

func (x *UsersRoles) ProtoReflect() protoreflect.Message {
	mi := &file_RBAC_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersRoles.ProtoReflect.Descriptor instead.
func (*UsersRoles) Descriptor() ([]byte, []int) {
	return file_RBAC_proto_rawDescGZIP(), []int{12}
}

func (x *UsersRoles) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *UsersRoles) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_RBAC_proto protoreflect.FileDescriptor

var file_RBAC_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x52, 0x42,
	0x41, 0x43, 0x22, 0x1a, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x22, 0x1d,
	0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x42, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x17, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69,
	0x64, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x1d,
	0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x07, 0x0a,
	0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1a, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x1d, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x22, 0x33, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x39, 0x0a, 0x0b, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x22, 0x31, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x32, 0xbb, 0x02,
	0x0a, 0x04, 0x52, 0x42, 0x41, 0x43, 0x12, 0x25, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x12, 0x0a, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x75, 0x69, 0x64, 0x73, 0x1a, 0x0b,
	0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x12, 0x26, 0x0a,
	0x09, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x0a, 0x2e, 0x52, 0x42, 0x41,
	0x43, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x1a, 0x0b, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x0b, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x1a, 0x0b,
	0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2b, 0x0a,
	0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x0b,
	0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x73, 0x1a, 0x0b, 0x2e, 0x52, 0x42,
	0x41, 0x43, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x11, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x11, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x0f, 0x63, 0x68, 0x65, 0x61, 0x6b, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x11, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x1a, 0x0b, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12,
	0x0b, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x52,
	0x42, 0x41, 0x43, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2f, 0x52, 0x42, 0x41, 0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RBAC_proto_rawDescOnce sync.Once
	file_RBAC_proto_rawDescData = file_RBAC_proto_rawDesc
)

func file_RBAC_proto_rawDescGZIP() []byte {
	file_RBAC_proto_rawDescOnce.Do(func() {
		file_RBAC_proto_rawDescData = protoimpl.X.CompressGZIP(file_RBAC_proto_rawDescData)
	})
	return file_RBAC_proto_rawDescData
}

var file_RBAC_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_RBAC_proto_goTypes = []interface{}{
	(*Bool)(nil),       // 0: RBAC.Bool
	(*Bools)(nil),      // 1: RBAC.Bools
	(*Uid)(nil),        // 2: RBAC.uid
	(*Uids)(nil),       // 3: RBAC.uids
	(*Role)(nil),       // 4: RBAC.role
	(*Roles)(nil),      // 5: RBAC.roles
	(*Empty)(nil),      // 6: RBAC.empty
	(*Path)(nil),       // 7: RBAC.path
	(*Paths)(nil),      // 8: RBAC.paths
	(*RolePath)(nil),   // 9: RBAC.role_path
	(*RolesPaths)(nil), // 10: RBAC.roles_paths
	(*UserRole)(nil),   // 11: RBAC.user_role
	(*UsersRoles)(nil), // 12: RBAC.users_roles
}
var file_RBAC_proto_depIdxs = []int32{
	3,  // 0: RBAC.RBAC.get_role:input_type -> RBAC.uids
	7,  // 1: RBAC.RBAC.get_paths:input_type -> RBAC.path
	5,  // 2: RBAC.RBAC.add_role:input_type -> RBAC.roles
	8,  // 3: RBAC.RBAC.refresh_paths:input_type -> RBAC.paths
	12, // 4: RBAC.RBAC.refresh_user_role:input_type -> RBAC.users_roles
	10, // 5: RBAC.RBAC.cheak_role_path:input_type -> RBAC.roles_paths
	6,  // 6: RBAC.RBAC.Cache:input_type -> RBAC.empty
	5,  // 7: RBAC.RBAC.get_role:output_type -> RBAC.roles
	8,  // 8: RBAC.RBAC.get_paths:output_type -> RBAC.paths
	6,  // 9: RBAC.RBAC.add_role:output_type -> RBAC.empty
	6,  // 10: RBAC.RBAC.refresh_paths:output_type -> RBAC.empty
	6,  // 11: RBAC.RBAC.refresh_user_role:output_type -> RBAC.empty
	1,  // 12: RBAC.RBAC.cheak_role_path:output_type -> RBAC.Bools
	6,  // 13: RBAC.RBAC.Cache:output_type -> RBAC.empty
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_RBAC_proto_init() }
func file_RBAC_proto_init() {
	if File_RBAC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RBAC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bools); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RBAC_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersRoles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RBAC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RBAC_proto_goTypes,
		DependencyIndexes: file_RBAC_proto_depIdxs,
		MessageInfos:      file_RBAC_proto_msgTypes,
	}.Build()
	File_RBAC_proto = out.File
	file_RBAC_proto_rawDesc = nil
	file_RBAC_proto_goTypes = nil
	file_RBAC_proto_depIdxs = nil
}
