// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: KetangpaiDB.proto

package KetangpaiDB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{0}
}

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{1}
}

func (x *Name) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Names struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *Names) Reset() {
	*x = Names{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Names) ProtoMessage() {}

func (x *Names) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Names.ProtoReflect.Descriptor instead.
func (*Names) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{2}
}

func (x *Names) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type Uid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Uid) Reset() {
	*x = Uid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uid) ProtoMessage() {}

func (x *Uid) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uid.ProtoReflect.Descriptor instead.
func (*Uid) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{3}
}

func (x *Uid) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Uids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
}

func (x *Uids) Reset() {
	*x = Uids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uids) ProtoMessage() {}

func (x *Uids) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uids.ProtoReflect.Descriptor instead.
func (*Uids) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{4}
}

func (x *Uids) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` //本产品的ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id      uint32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`           //用户中心的ID
	Classid uint32 `protobuf:"varint,4,opt,name=classid,proto3" json:"classid,omitempty"` //所属班级
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetClassid() uint32 {
	if x != nil {
		return x.Classid
	}
	return 0
}

type Users struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *Users) Reset() {
	*x = Users{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{6}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Classid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classid uint32 `protobuf:"varint,1,opt,name=classid,proto3" json:"classid,omitempty"`
}

func (x *Classid) Reset() {
	*x = Classid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Classid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classid) ProtoMessage() {}

func (x *Classid) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classid.ProtoReflect.Descriptor instead.
func (*Classid) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{7}
}

func (x *Classid) GetClassid() uint32 {
	if x != nil {
		return x.Classid
	}
	return 0
}

type Classname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Classname) Reset() {
	*x = Classname{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Classname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classname) ProtoMessage() {}

func (x *Classname) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classname.ProtoReflect.Descriptor instead.
func (*Classname) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{8}
}

func (x *Classname) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Classid uint32 `protobuf:"varint,2,opt,name=classid,proto3" json:"classid,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{9}
}

func (x *Member) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Member) GetClassid() uint32 {
	if x != nil {
		return x.Classid
	}
	return 0
}

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classid  uint32   `protobuf:"varint,1,opt,name=classid,proto3" json:"classid,omitempty"`
	Teacher  uint32   `protobuf:"varint,2,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Name     string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Students []uint32 `protobuf:"varint,4,rep,packed,name=students,proto3" json:"students,omitempty"`
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KetangpaiDB_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_KetangpaiDB_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_KetangpaiDB_proto_rawDescGZIP(), []int{10}
}

func (x *Class) GetClassid() uint32 {
	if x != nil {
		return x.Classid
	}
	return 0
}

func (x *Class) GetTeacher() uint32 {
	if x != nil {
		return x.Teacher
	}
	return 0
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetStudents() []uint32 {
	if x != nil {
		return x.Students
	}
	return nil
}

var File_KetangpaiDB_proto protoreflect.FileDescriptor

var file_KetangpaiDB_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42,
	0x22, 0x07, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1a, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a,
	0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x64, 0x22, 0x30, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x65, 0x74, 0x61,
	0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x23, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64, 0x22,
	0x6b, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xcf, 0x06, 0x0a,
	0x0b, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x12, 0x35, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x6b, 0x65,
	0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x11,
	0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69,
	0x44, 0x42, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d, 0x67, 0x65,
	0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x11, 0x2e, 0x6b, 0x65,
	0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x11,
	0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x11, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69,
	0x44, 0x42, 0x2e, 0x75, 0x69, 0x64, 0x73, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67,
	0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x0d, 0x73, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x11,
	0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x1a, 0x11, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x10, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e,
	0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x69, 0x64, 0x1a, 0x14, 0x2e, 0x6b, 0x65, 0x74,
	0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x64,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42,
	0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70,
	0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0e,
	0x67, 0x65, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x64, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69,
	0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x11, 0x67, 0x65,
	0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x14, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x64, 0x1a, 0x10, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61,
	0x69, 0x44, 0x42, 0x2e, 0x75, 0x69, 0x64, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e, 0x67, 0x65, 0x74,
	0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x6b, 0x65,
	0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x64, 0x1a, 0x16, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0e, 0x64,
	0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x2e,
	0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x64, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44,
	0x42, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x15, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42,
	0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70,
	0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0c,
	0x66, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x2e, 0x6b,
	0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x75, 0x69, 0x64, 0x1a, 0x12,
	0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x5f, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x13, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44,
	0x42, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x12, 0x2e, 0x6b, 0x65, 0x74, 0x61, 0x6e,
	0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x4b, 0x65, 0x74, 0x61, 0x6e, 0x67, 0x70, 0x61, 0x69, 0x44, 0x42, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_KetangpaiDB_proto_rawDescOnce sync.Once
	file_KetangpaiDB_proto_rawDescData = file_KetangpaiDB_proto_rawDesc
)

func file_KetangpaiDB_proto_rawDescGZIP() []byte {
	file_KetangpaiDB_proto_rawDescOnce.Do(func() {
		file_KetangpaiDB_proto_rawDescData = protoimpl.X.CompressGZIP(file_KetangpaiDB_proto_rawDescData)
	})
	return file_KetangpaiDB_proto_rawDescData
}

var file_KetangpaiDB_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_KetangpaiDB_proto_goTypes = []interface{}{
	(*Empty)(nil),     // 0: ketangpaiDB.empty
	(*Name)(nil),      // 1: ketangpaiDB.name
	(*Names)(nil),     // 2: ketangpaiDB.names
	(*Uid)(nil),       // 3: ketangpaiDB.uid
	(*Uids)(nil),      // 4: ketangpaiDB.uids
	(*User)(nil),      // 5: ketangpaiDB.user
	(*Users)(nil),     // 6: ketangpaiDB.users
	(*Classid)(nil),   // 7: ketangpaiDB.classid
	(*Classname)(nil), // 8: ketangpaiDB.classname
	(*Member)(nil),    // 9: ketangpaiDB.member
	(*Class)(nil),     // 10: ketangpaiDB.class
}
var file_KetangpaiDB_proto_depIdxs = []int32{
	5,  // 0: ketangpaiDB.users.users:type_name -> ketangpaiDB.user
	5,  // 1: ketangpaiDB.ketangpaiDB.create_user:input_type -> ketangpaiDB.user
	0,  // 2: ketangpaiDB.ketangpaiDB.get_users:input_type -> ketangpaiDB.empty
	5,  // 3: ketangpaiDB.ketangpaiDB.get_user_info:input_type -> ketangpaiDB.user
	4,  // 4: ketangpaiDB.ketangpaiDB.get_user_name:input_type -> ketangpaiDB.uids
	5,  // 5: ketangpaiDB.ketangpaiDB.set_user_name:input_type -> ketangpaiDB.user
	3,  // 6: ketangpaiDB.ketangpaiDB.get_user_class:input_type -> ketangpaiDB.uid
	10, // 7: ketangpaiDB.ketangpaiDB.create_class:input_type -> ketangpaiDB.class
	7,  // 8: ketangpaiDB.ketangpaiDB.get_class_info:input_type -> ketangpaiDB.classid
	7,  // 9: ketangpaiDB.ketangpaiDB.get_class_teacher:input_type -> ketangpaiDB.classid
	7,  // 10: ketangpaiDB.ketangpaiDB.get_class_name:input_type -> ketangpaiDB.classid
	7,  // 11: ketangpaiDB.ketangpaiDB.dissolve_class:input_type -> ketangpaiDB.classid
	10, // 12: ketangpaiDB.ketangpaiDB.refreshing_class_data:input_type -> ketangpaiDB.class
	3,  // 13: ketangpaiDB.ketangpaiDB.fire_student:input_type -> ketangpaiDB.uid
	9,  // 14: ketangpaiDB.ketangpaiDB.add_student:input_type -> ketangpaiDB.member
	5,  // 15: ketangpaiDB.ketangpaiDB.create_user:output_type -> ketangpaiDB.user
	6,  // 16: ketangpaiDB.ketangpaiDB.get_users:output_type -> ketangpaiDB.users
	5,  // 17: ketangpaiDB.ketangpaiDB.get_user_info:output_type -> ketangpaiDB.user
	2,  // 18: ketangpaiDB.ketangpaiDB.get_user_name:output_type -> ketangpaiDB.names
	1,  // 19: ketangpaiDB.ketangpaiDB.set_user_name:output_type -> ketangpaiDB.name
	7,  // 20: ketangpaiDB.ketangpaiDB.get_user_class:output_type -> ketangpaiDB.classid
	10, // 21: ketangpaiDB.ketangpaiDB.create_class:output_type -> ketangpaiDB.class
	10, // 22: ketangpaiDB.ketangpaiDB.get_class_info:output_type -> ketangpaiDB.class
	3,  // 23: ketangpaiDB.ketangpaiDB.get_class_teacher:output_type -> ketangpaiDB.uid
	8,  // 24: ketangpaiDB.ketangpaiDB.get_class_name:output_type -> ketangpaiDB.classname
	0,  // 25: ketangpaiDB.ketangpaiDB.dissolve_class:output_type -> ketangpaiDB.empty
	10, // 26: ketangpaiDB.ketangpaiDB.refreshing_class_data:output_type -> ketangpaiDB.class
	10, // 27: ketangpaiDB.ketangpaiDB.fire_student:output_type -> ketangpaiDB.class
	10, // 28: ketangpaiDB.ketangpaiDB.add_student:output_type -> ketangpaiDB.class
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_KetangpaiDB_proto_init() }
func file_KetangpaiDB_proto_init() {
	if File_KetangpaiDB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_KetangpaiDB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Names); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Users); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Classid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Classname); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KetangpaiDB_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KetangpaiDB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_KetangpaiDB_proto_goTypes,
		DependencyIndexes: file_KetangpaiDB_proto_depIdxs,
		MessageInfos:      file_KetangpaiDB_proto_msgTypes,
	}.Build()
	File_KetangpaiDB_proto = out.File
	file_KetangpaiDB_proto_rawDesc = nil
	file_KetangpaiDB_proto_goTypes = nil
	file_KetangpaiDB_proto_depIdxs = nil
}
