// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: TestBank.proto

package TestBank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ans string `protobuf:"bytes,1,opt,name=ans,proto3" json:"ans,omitempty"`
}

func (x *Ans) Reset() {
	*x = Ans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ans) ProtoMessage() {}

func (x *Ans) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ans.ProtoReflect.Descriptor instead.
func (*Ans) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{0}
}

func (x *Ans) GetAns() string {
	if x != nil {
		return x.Ans
	}
	return ""
}

type Anss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anss []string `protobuf:"bytes,1,rep,name=anss,proto3" json:"anss,omitempty"`
}

func (x *Anss) Reset() {
	*x = Anss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Anss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anss) ProtoMessage() {}

func (x *Anss) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anss.ProtoReflect.Descriptor instead.
func (*Anss) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{1}
}

func (x *Anss) GetAnss() []string {
	if x != nil {
		return x.Anss
	}
	return nil
}

type Testid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Testid) Reset() {
	*x = Testid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Testid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Testid) ProtoMessage() {}

func (x *Testid) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Testid.ProtoReflect.Descriptor instead.
func (*Testid) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{2}
}

func (x *Testid) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Testids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Testids []uint32 `protobuf:"varint,1,rep,packed,name=testids,proto3" json:"testids,omitempty"`
}

func (x *Testids) Reset() {
	*x = Testids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Testids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Testids) ProtoMessage() {}

func (x *Testids) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Testids.ProtoReflect.Descriptor instead.
func (*Testids) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{3}
}

func (x *Testids) GetTestids() []uint32 {
	if x != nil {
		return x.Testids
	}
	return nil
}

type Testconf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubjectiveItem uint32 `protobuf:"varint,1,opt,name=subjective_item,json=subjectiveItem,proto3" json:"subjective_item,omitempty"` //主观题的数量
	ObjectiveItem  uint32 `protobuf:"varint,2,opt,name=objective_item,json=objectiveItem,proto3" json:"objective_item,omitempty"`    //客观题的数量
	Discipline     uint32 `protobuf:"varint,3,opt,name=discipline,proto3" json:"discipline,omitempty"`                               //学科
}

func (x *Testconf) Reset() {
	*x = Testconf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Testconf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Testconf) ProtoMessage() {}

func (x *Testconf) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Testconf.ProtoReflect.Descriptor instead.
func (*Testconf) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{4}
}

func (x *Testconf) GetSubjectiveItem() uint32 {
	if x != nil {
		return x.SubjectiveItem
	}
	return 0
}

func (x *Testconf) GetObjectiveItem() uint32 {
	if x != nil {
		return x.ObjectiveItem
	}
	return 0
}

func (x *Testconf) GetDiscipline() uint32 {
	if x != nil {
		return x.Discipline
	}
	return 0
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                 //自身ID
	Typ        uint32 `protobuf:"varint,2,opt,name=typ,proto3" json:"typ,omitempty"`               //类型-主观题/客观题
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`        //内容
	Ans        string `protobuf:"bytes,4,opt,name=ans,proto3" json:"ans,omitempty"`                //答案(如果有)
	Name       string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`              //名字-题目描述
	Uploader   uint32 `protobuf:"varint,6,opt,name=uploader,proto3" json:"uploader,omitempty"`     //上传者
	Discipline uint32 `protobuf:"varint,7,opt,name=discipline,proto3" json:"discipline,omitempty"` //学科
	Withans    bool   `protobuf:"varint,8,opt,name=withans,proto3" json:"withans,omitempty"`       //附带答案？
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{5}
}

func (x *Test) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Test) GetTyp() uint32 {
	if x != nil {
		return x.Typ
	}
	return 0
}

func (x *Test) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Test) GetAns() string {
	if x != nil {
		return x.Ans
	}
	return ""
}

func (x *Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Test) GetUploader() uint32 {
	if x != nil {
		return x.Uploader
	}
	return 0
}

func (x *Test) GetDiscipline() uint32 {
	if x != nil {
		return x.Discipline
	}
	return 0
}

func (x *Test) GetWithans() bool {
	if x != nil {
		return x.Withans
	}
	return false
}

type Tests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tests []string `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"` //JSON文本
	Ans   []byte   `protobuf:"bytes,2,opt,name=ans,proto3" json:"ans,omitempty"`     //答案 JSON-byte
}

func (x *Tests) Reset() {
	*x = Tests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestBank_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tests) ProtoMessage() {}

func (x *Tests) ProtoReflect() protoreflect.Message {
	mi := &file_TestBank_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tests.ProtoReflect.Descriptor instead.
func (*Tests) Descriptor() ([]byte, []int) {
	return file_TestBank_proto_rawDescGZIP(), []int{6}
}

func (x *Tests) GetTests() []string {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *Tests) GetAns() []byte {
	if x != nil {
		return x.Ans
	}
	return nil
}

var File_TestBank_proto protoreflect.FileDescriptor

var file_TestBank_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x22, 0x17, 0x0a, 0x03, 0x61, 0x6e,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x6e, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x61, 0x6e, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x6e, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x6e, 0x73, 0x73, 0x22,
	0x18, 0x0a, 0x06, 0x74, 0x65, 0x73, 0x74, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x07, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x69, 0x64, 0x73, 0x22, 0x7a,
	0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69,
	0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x64, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x04, 0x74,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6e,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x69, 0x74, 0x68, 0x61, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x77, 0x69, 0x74, 0x68, 0x61, 0x6e, 0x73, 0x22, 0x2f, 0x0a, 0x05, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x6e, 0x73, 0x32, 0xd2, 0x01, 0x0a,
	0x08, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x06, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x0e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x10, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x64, 0x1a, 0x0e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x36, 0x0a, 0x0d, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x1a, 0x0f,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x22,
	0x00, 0x12, 0x2e, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x12, 0x11, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x64, 0x73, 0x1a,
	0x0e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x61, 0x6e, 0x73, 0x73, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x54, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TestBank_proto_rawDescOnce sync.Once
	file_TestBank_proto_rawDescData = file_TestBank_proto_rawDesc
)

func file_TestBank_proto_rawDescGZIP() []byte {
	file_TestBank_proto_rawDescOnce.Do(func() {
		file_TestBank_proto_rawDescData = protoimpl.X.CompressGZIP(file_TestBank_proto_rawDescData)
	})
	return file_TestBank_proto_rawDescData
}

var file_TestBank_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_TestBank_proto_goTypes = []interface{}{
	(*Ans)(nil),      // 0: TestBank.ans
	(*Anss)(nil),     // 1: TestBank.anss
	(*Testid)(nil),   // 2: TestBank.testid
	(*Testids)(nil),  // 3: TestBank.testids
	(*Testconf)(nil), // 4: TestBank.testconf
	(*Test)(nil),     // 5: TestBank.test
	(*Tests)(nil),    // 6: TestBank.tests
}
var file_TestBank_proto_depIdxs = []int32{
	5, // 0: TestBank.TestBank.upload:input_type -> TestBank.test
	2, // 1: TestBank.TestBank.download:input_type -> TestBank.testid
	4, // 2: TestBank.TestBank.generate_test:input_type -> TestBank.testconf
	3, // 3: TestBank.TestBank.get_ans:input_type -> TestBank.testids
	5, // 4: TestBank.TestBank.upload:output_type -> TestBank.test
	5, // 5: TestBank.TestBank.download:output_type -> TestBank.test
	6, // 6: TestBank.TestBank.generate_test:output_type -> TestBank.tests
	1, // 7: TestBank.TestBank.get_ans:output_type -> TestBank.anss
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TestBank_proto_init() }
func file_TestBank_proto_init() {
	if File_TestBank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TestBank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Anss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Testid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Testids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Testconf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TestBank_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TestBank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TestBank_proto_goTypes,
		DependencyIndexes: file_TestBank_proto_depIdxs,
		MessageInfos:      file_TestBank_proto_msgTypes,
	}.Build()
	File_TestBank_proto = out.File
	file_TestBank_proto_rawDesc = nil
	file_TestBank_proto_goTypes = nil
	file_TestBank_proto_depIdxs = nil
}
