// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: RankingList.proto

package RankingList

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{0}
}

type Listname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Listname) Reset() {
	*x = Listname{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listname) ProtoMessage() {}

func (x *Listname) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listname.ProtoReflect.Descriptor instead.
func (*Listname) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{1}
}

func (x *Listname) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Members struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //榜单名
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *Members) Reset() {
	*x = Members{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Members) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Members) ProtoMessage() {}

func (x *Members) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Members.ProtoReflect.Descriptor instead.
func (*Members) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{2}
}

func (x *Members) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Members) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type Rankings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank []int64 `protobuf:"varint,1,rep,packed,name=rank,proto3" json:"rank,omitempty"`
}

func (x *Rankings) Reset() {
	*x = Rankings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rankings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rankings) ProtoMessage() {}

func (x *Rankings) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rankings.ProtoReflect.Descriptor instead.
func (*Rankings) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{3}
}

func (x *Rankings) GetRank() []int64 {
	if x != nil {
		return x.Rank
	}
	return nil
}

type Flushin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`              //刷新的表
	Increment int32  `protobuf:"varint,2,opt,name=increment,proto3" json:"increment,omitempty"` //刷新量
	Member    string `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`        //刷新对象
}

func (x *Flushin) Reset() {
	*x = Flushin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flushin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flushin) ProtoMessage() {}

func (x *Flushin) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flushin.ProtoReflect.Descriptor instead.
func (*Flushin) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{4}
}

func (x *Flushin) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flushin) GetIncrement() int32 {
	if x != nil {
		return x.Increment
	}
	return 0
}

func (x *Flushin) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type Flushout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member  string `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`    //刷新对象
	Ranking int64  `protobuf:"varint,2,opt,name=ranking,proto3" json:"ranking,omitempty"` //刷新后排名
}

func (x *Flushout) Reset() {
	*x = Flushout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flushout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flushout) ProtoMessage() {}

func (x *Flushout) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flushout.ProtoReflect.Descriptor instead.
func (*Flushout) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{5}
}

func (x *Flushout) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *Flushout) GetRanking() int64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

type Listinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //榜名
	List []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` //榜单-仅对象/对象+分值、、、
}

func (x *Listinfo) Reset() {
	*x = Listinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RankingList_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listinfo) ProtoMessage() {}

func (x *Listinfo) ProtoReflect() protoreflect.Message {
	mi := &file_RankingList_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listinfo.ProtoReflect.Descriptor instead.
func (*Listinfo) Descriptor() ([]byte, []int) {
	return file_RankingList_proto_rawDescGZIP(), []int{6}
}

func (x *Listinfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listinfo) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var File_RankingList_proto protoreflect.FileDescriptor

var file_RankingList_proto_rawDesc = []byte{
	0x0a, 0x11, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x07, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1e, 0x0a, 0x08, 0x6c, 0x69, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61,
	0x6e, 0x6b, 0x22, 0x51, 0x0a, 0x07, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x08, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x6f, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x22, 0x32, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xfd, 0x01, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x66, 0x6c, 0x75, 0x73, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x2e, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x69, 0x6e, 0x1a, 0x15, 0x2e, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x6f, 0x75,
	0x74, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x15, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x15, 0x2e, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x6c, 0x69, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x12, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x67, 0x65,
	0x74, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x1a, 0x15,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x72, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RankingList_proto_rawDescOnce sync.Once
	file_RankingList_proto_rawDescData = file_RankingList_proto_rawDesc
)

func file_RankingList_proto_rawDescGZIP() []byte {
	file_RankingList_proto_rawDescOnce.Do(func() {
		file_RankingList_proto_rawDescData = protoimpl.X.CompressGZIP(file_RankingList_proto_rawDescData)
	})
	return file_RankingList_proto_rawDescData
}

var file_RankingList_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_RankingList_proto_goTypes = []interface{}{
	(*Empty)(nil),    // 0: RankingList.empty
	(*Listname)(nil), // 1: RankingList.listname
	(*Members)(nil),  // 2: RankingList.members
	(*Rankings)(nil), // 3: RankingList.rankings
	(*Flushin)(nil),  // 4: RankingList.flushin
	(*Flushout)(nil), // 5: RankingList.flushout
	(*Listinfo)(nil), // 6: RankingList.listinfo
}
var file_RankingList_proto_depIdxs = []int32{
	4, // 0: RankingList.RankingList.flushlist:input_type -> RankingList.flushin
	1, // 1: RankingList.RankingList.getlistinfo:input_type -> RankingList.listname
	1, // 2: RankingList.RankingList.dellist:input_type -> RankingList.listname
	2, // 3: RankingList.RankingList.getranking:input_type -> RankingList.members
	5, // 4: RankingList.RankingList.flushlist:output_type -> RankingList.flushout
	6, // 5: RankingList.RankingList.getlistinfo:output_type -> RankingList.listinfo
	0, // 6: RankingList.RankingList.dellist:output_type -> RankingList.empty
	3, // 7: RankingList.RankingList.getranking:output_type -> RankingList.rankings
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RankingList_proto_init() }
func file_RankingList_proto_init() {
	if File_RankingList_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RankingList_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listname); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Members); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rankings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flushin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flushout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RankingList_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RankingList_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RankingList_proto_goTypes,
		DependencyIndexes: file_RankingList_proto_depIdxs,
		MessageInfos:      file_RankingList_proto_msgTypes,
	}.Build()
	File_RankingList_proto = out.File
	file_RankingList_proto_rawDesc = nil
	file_RankingList_proto_goTypes = nil
	file_RankingList_proto_depIdxs = nil
}
