// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: Filter.proto

package Filter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FilterData) Reset() {
	*x = FilterData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterData) ProtoMessage() {}

func (x *FilterData) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterData.ProtoReflect.Descriptor instead.
func (*FilterData) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_Filter_proto protoreflect.FileDescriptor

var file_Filter_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20,
	0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x32, 0x52, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x21, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Filter_proto_rawDescOnce sync.Once
	file_Filter_proto_rawDescData = file_Filter_proto_rawDesc
)

func file_Filter_proto_rawDescGZIP() []byte {
	file_Filter_proto_rawDescOnce.Do(func() {
		file_Filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_Filter_proto_rawDescData)
	})
	return file_Filter_proto_rawDescData
}

var file_Filter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Filter_proto_goTypes = []interface{}{
	(*FilterData)(nil), // 0: FilterData
}
var file_Filter_proto_depIdxs = []int32{
	0, // 0: Filter.Process:input_type -> FilterData
	0, // 1: Filter.Add:input_type -> FilterData
	0, // 2: Filter.Process:output_type -> FilterData
	0, // 3: Filter.Add:output_type -> FilterData
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Filter_proto_init() }
func file_Filter_proto_init() {
	if File_Filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Filter_proto_goTypes,
		DependencyIndexes: file_Filter_proto_depIdxs,
		MessageInfos:      file_Filter_proto_msgTypes,
	}.Build()
	File_Filter_proto = out.File
	file_Filter_proto_rawDesc = nil
	file_Filter_proto_goTypes = nil
	file_Filter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FilterClient is the client API for Filter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilterClient interface {
	Process(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error)
	Add(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error)
}

type filterClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterClient(cc grpc.ClientConnInterface) FilterClient {
	return &filterClient{cc}
}

func (c *filterClient) Process(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error) {
	out := new(FilterData)
	err := c.cc.Invoke(ctx, "/Filter/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterClient) Add(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error) {
	out := new(FilterData)
	err := c.cc.Invoke(ctx, "/Filter/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServer is the server API for Filter service.
type FilterServer interface {
	Process(context.Context, *FilterData) (*FilterData, error)
	Add(context.Context, *FilterData) (*FilterData, error)
}

// UnimplementedFilterServer can be embedded to have forward compatible implementations.
type UnimplementedFilterServer struct {
}

func (*UnimplementedFilterServer) Process(context.Context, *FilterData) (*FilterData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedFilterServer) Add(context.Context, *FilterData) (*FilterData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterFilterServer(s *grpc.Server, srv FilterServer) {
	s.RegisterService(&_Filter_serviceDesc, srv)
}

func _Filter_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Filter/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).Process(ctx, req.(*FilterData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filter_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Filter/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).Add(ctx, req.(*FilterData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Filter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Filter",
	HandlerType: (*FilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Filter_Process_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Filter_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Filter.proto",
}
